version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "annabackend"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1acf2bwpbbez2"
s3_prefix = "annabackend"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
